#!/bin/sh -e
#

cd `dirname $0`
export sdir=`pwd`

###########################################################
# install apps

chmod +x `grep -rl '^#!/bin' ./`

for app in wkit $@; do
    echo "> install app $app ..."
    if [ -x $sdir/$app/install ]; then
        cd $sdir/$app && ./install
    fi
    echo "> install app $app done"
done

###########################################################
# fix permissions

chmod 0644 /etc/logrotate.d/*
chmod 0755 /etc/wkit.d/*
