#!/bin/sh -e
#

cd `dirname $0`
export sdir=`pwd`

###########################################################
# install apps

chmod +x `grep -rl '^#!/bin' ./`

for app in wkit $@; do
    echo "install $app ..."
    if [ -x $sdir/$app/install ]; then
        cd $sdir/$app && ./install
    fi
    if [ -x /usr/wkit/services/$app ]; then
        sed -i 's/\(WBX_APPS=".*\)"/\1 '$app'"/' /etc/wkit-env
    fi
done
