#!/bin/sh -e
#

self=$0
if [ -L $self ]; then
    self=`readlink $self`
fi

sdir=`dirname $self`

###########################################################
# install apps

chmod +x `grep -rl '^#!/bin' ./`

for app in wkit goaccess mysql redis nginx php7; do
    cd $sdir/$app && ./install
done
