#!/bin/sh
#

. /usr/wkit/app-rc

#====================================================================#

APP_NAME=php84

APP_USER=daemon
APP_GROUP=daemon

APP_BIN_FILE=/usr/sbin/php-fpm83
APP_PID_FILE=/var/run/php84/fpm.pid

#====================================================================#

app_reload() {

    kill -USR2 `cat $APP_PID_FILE`

}

app_prepare() {

    for POOL in `ls /etc/php84/php-fpm.d/`; do
        POOL=${POOL%.*}
        mkdir -p /var/www/${POOL}
        mkdir -p /var/log/php84/${POOL}
        mkdir -p /var/tmp/php84/${POOL}/upload
        mkdir -p /var/tmp/php84/${POOL}/session
    done

    app_ownmod /var/www &

    app_varfix log run tmp

}

#====================================================================#

app_do $1
