#!/bin/sh -e
#

apk add --no-cache php82 php82-fpm \
    php82-bcmath \
    php82-bz2 \
    php82-curl \
    php82-ctype \
    php82-dom \
    php82-exif \
    php82-fileinfo \
    php82-ftp \
    php82-gd \
    php82-gettext \
    php82-iconv \
    php82-json \
    php82-mbstring \
    php82-mysqli \
    php82-mysqlnd \
    php82-opcache \
    php82-openssl \
    php82-pecl-redis \
    php82-pdo_mysql \
    php82-pdo_sqlite \
    php82-session \
    php82-shmop \
    php82-simplexml \
    php82-sockets \
    php82-sqlite3 \
    php82-tokenizer \
    php82-xml \
    php82-xmlreader \
    php82-xmlwriter \
    php82-xsl \
    php82-zip

rm -rf /etc/php82/php-fpm.d
rm -rf /var/lib/php82

# fix nginx config

sed -i 's#php/#php82/#g' /etc/nginx/http.d/server_fastcgi_php
sed -i 's#php/#php82/#g' /etc/nginx/http.d/server_status

# add profiles

cp -av etc /
cp -av usr /
