#!/bin/sh
#

wkit goaccess restart

###

. /etc/conf.d/goaccess

if [ ! -d $GOACCESS_DATA_DIR/archive ]; then
    mkdir -p $GOACCESS_DATA_DIR/archive
fi

###

logs=`find /var/log/nginx -name "access.log-*[0-9]"`

db_path=$GOACCESS_DATA_DIR/database
archive=$GOACCESS_DATA_DIR/archive/${logs##*-}

goaccess $logs --process-and-exit --persist --restore --db-path=$db_path

goaccess --output $archive.html --restore --db-path=$db_path
goaccess --output $archive.json --restore --db-path=$db_path
