#!/bin/sh
#

kill `pidof goaccess`
/etc/local.d/s8-goaccess

###

. /etc/goaccess/env-vars

dbp=$DATA_DIR/database
out=$DATA_DIR/archive/${log##*-}
log=`find /var/log/nginx -name "access.log-*[0-9]"`

goaccess $log --process-and-exit --agent-list --real-os --persist --restore --db-path=$dbp

goaccess -o $out.json --agent-list --real-os --restore --db-path=$dbp
goaccess -o $out.html --agent-list --real-os --restore --db-path=$dbp
