#!/bin/sh
#

wkit goaccess restart

###

. /etc/conf.d/goaccess

if [ ! -d $GOACCESS_DATA_DIR/archive ]; then
    mkdir -p $GOACCESS_DATA_DIR/archive
fi

###

log=`find /var/log/nginx -name "access.log-*[0-9]"`

dbp=$GOACCESS_DATA_DIR/database
out=$GOACCESS_DATA_DIR/archive/${log##*-}

goaccess $log --process-and-exit --agent-list --real-os --persist --restore --db-path=$dbp

goaccess -o $out.json --agent-list --real-os --restore --db-path=$dbp
goaccess -o $out.html --agent-list --real-os --restore --db-path=$dbp
