#!/bin/sh
#

. /etc/goaccess/env-vars

if grep -q access_log /etc/nginx/conf.d/http.conf; then
    sed -i '/access_log/d' /etc/nginx/conf.d/http.conf
    echo "access_log $LOG_FILE main;" > /etc/nginx/http.d/logger.conf
fi

if [ ! -e /etc/nginx/http.d/auth_basic ]; then
    echo admin:$(echo $REPORT_PWD | openssl passwd -stdin -apr1) > /etc/nginx/http.d/auth_basic
fi
