#!/bin/sh
#

. /etc/goaccess/env-vars

if grep -q DATA_DIR /etc/goaccess/goaccess.conf; then
    sed -i "s#\$DATA_DIR#${DATA_DIR}#" /etc/goaccess/goaccess.conf
fi

if grep -q REPORT_URL /etc/goaccess/goaccess.conf; then
    sed -i "s#\$REPORT_URL#${REPORT_URL}#" /etc/goaccess/goaccess.conf
fi

if [ ! -d $DATA_DIR ]; then
    mkdir -p $DATA_DIR/archive $DATA_DIR/database $DATA_DIR/report
fi

goaccess $LOG_FILE --output=$DATA_DIR/report/index.html
