#!/bin/sh
#

. /usr/wkit/app-rc
. /etc/conf.d/goaccess

#====================================================================#

APP_NAME=goaccess

APP_BIN_FILE=/usr/bin/goaccess
APP_PID_FILE=/var/run/goaccess.pid

#====================================================================#

app_start() {

    if [ ! -d $GOACCESS_DATA_DIR ]; then
        mkdir -p $GOACCESS_DATA_DIR/report $GOACCESS_DATA_DIR/database
    fi

    $APP_BIN_FILE $GOACCESS_LOG_FILE --daemonize --real-time-html \
        --pid-file $APP_PID_FILE --output $GOACCESS_DATA_DIR/report/index.html

}

app_stop() {

    kill -TERM `cat $APP_PID_FILE`

    [ -f $APP_PID_FILE ] &&  rm $APP_PID_FILE

}

app_prepare() {

    # add geoip database

    if [ ! -f /usr/share/geoip/city-lite.mmdb ]; then
        wkit geoip-update
    fi

    # fix goaccess config

    if grep -q GOACCESS_DATA_DIR /etc/goaccess/goaccess.conf; then
        sed -i "s#\$GOACCESS_DATA_DIR#${GOACCESS_DATA_DIR}#" /etc/goaccess/goaccess.conf
    fi
    if grep -q GOACCESS_REPORT_URL /etc/goaccess/goaccess.conf; then
        sed -i "s#\$GOACCESS_REPORT_URL#${GOACCESS_REPORT_URL}#" /etc/goaccess/goaccess.conf
    fi

    # fix nginx proxy config

    if [ ! -e /etc/nginx/http.d/goaccess_auth ]; then
        echo report:$(echo $GOACCESS_REPORT_PWD | openssl passwd -stdin -apr1) >/etc/nginx/http.d/goaccess_auth
    fi

    if grep -q GOACCESS_DATA_DIR /etc/nginx/http.d/server_goaccess; then
        sed -i "s#\$GOACCESS_DATA_DIR#${GOACCESS_DATA_DIR}#" /etc/nginx/http.d/server_goaccess
    fi

}

#====================================================================#

app_do $1
